import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#FF0000",
        padding: 24,
    },
    text: {
        fontSize: 20,
        color: "#FFF"
    },
    button: {
        backgroundColor: '#000',
        width: 56,
        height: 56,
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
    },
    input: {
        marginRight: 45,
        marginLeft: 45,
        marginTop: 80,
        height: 45,
        backgroundColor: '#000',
        borderRadius: 10,
        padding: 8,
        fontSize: 16,
        color: '#FFF',
    },
    passwordContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 45,
        marginLeft: 45,
        marginTop: 20,
        height: 45,
        backgroundColor: '#000',
        borderRadius: 10,
        paddingHorizontal: 8,
        borderWidth: 1,
    },
    inputPassword: {
        flex: 1,
        fontSize: 16,
        color: '#FFF',
    },
    eyeIcon: {
        padding: 5,
    },
    divider: {
        width: "80%",
        height: 2,
        backgroundColor: "#000",
        marginTop: 20,
        marginLeft: 36,
    },
    forgotPassword: {
        alignSelf: 'center',
        marginBottom: 20,
        marginLeft: 148,
        marginTop: 10,
    },
    forgotPasswordText: {
        color: '#000000',
        fontSize: 16,
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 20,
        width: '80%', 
        alignSelf: 'center',
    },
    loginButton: {
        flex: 1,
        backgroundColor: '#000000',
        paddingVertical: 15,
        borderRadius: 30,
        marginRight: 5,
    },
    registerButton: {
        flex: 1,
        backgroundColor: '#000000',
        paddingVertical: 15,
        borderRadius: 30,
        marginLeft: 5,
    },
    buttonText: {
        color: '#fff',
        fontSize: 16,
        textAlign: 'center',
    },
    googleButton: {
        flexDirection: 'row', 
        alignItems: 'center',
        backgroundColor: '#000000',
        paddingVertical: 12,
        borderRadius: 25,
        marginBottom: 30,
        marginTop: 50,
        width: '80%',
        alignSelf: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3.84,
        elevation: 5,
    },
    googleLogo: {
        width: 25,
        height: 25,
        marginLeft: 50
    },
    googleButtonText: {
        marginLeft: 17,
        color: '#ddd',
        fontSize: 17,
        textAlign: 'center',
    },
    logo: {
        width: '60%',
        height: 200,
        alignSelf: 'center',
        marginTop: 30,
    },
});
